# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode12.4
xcode_workspace: Example/MobilliumDateFormatter.xcworkspace
xcode_scheme: MobilliumDateFormatter-Example
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
before_install:
- pod install
