name: Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.1,name=iPhone 8']
        xcode: ['/Applications/Xcode_12.4.app/Contents/Developer']
    env:
      XC_VERSION: ${{ '12.4' }}
      XC_WORKSPACE: ${{ 'Example/MobilliumDateFormatter.xcworkspace' }}
      XC_SCHEME: ${{ 'MobilliumDateFormatter-Example' }}
    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s ${{ matrix.xcode }}"
    - name: Install Dependencies
      run: |
        cd Example
        pod install --repo-update
      env:
        DEVELOPER_DIR: ${{ matrix.xcode }}
    - name: Run Unit and UI Tests
      run: /usr/bin/xcodebuild test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination ${{ matrix.destination }}
