name: Tests

on: 
  push:
    branches: 
      - master

jobs:
  Darwin:
    name: Darwin
    runs-on: macos-latest
    env:
      XC_VERSION: ${{ '11.7' }}
      XC_WORKSPACE: ${{ 'Example/MobilliumDateFormatter.xcworkspace' }}
      XC_SCHEME: ${{ 'MobilliumDateFormatter-Example' }}
    steps:
    - uses: actions/checkout@v1
    - name: Bundle Install
      run: bundle install
    - name: Brew Upgrade
      run: |
        brew update-reset
        brew bundle --no-upgrade
    - name: Test iOS
      run: |
        xcodebuild clean build test -project $XC_WORKSPACE -scheme $XC_SCHEME -destination "$DESTINATION" | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-ios.json" xcpretty -f `xcpretty-json-formatter`
        bash <(curl -s https://codecov.io/bash) -cF ios -J 'MobilliumDateFormatter'
      env:
          SCHEME: XC_SCHEME
          DESTINATION: platform=iOS Simulator,name=iPhone 11
  CocoaPods:
    name: CocoaPods
    runs-on: macos-latest
    strategy:
      matrix:
        platform: ['ios']
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
    steps:
    - uses: actions/checkout@v1
    - name: Bundle Install
      run: bundle install
    - name: CocoaPods ${{ matrix.platform }}
      run: bundle exec pod lib lint --skip-tests --allow-warnings --verbose --platforms=${{ matrix.platform }} 
