name: Unit test
  
on:
 push:
   branches: [ master ]
     
jobs:
 build:

     runs-on: macos-latest
     env:
       XC_VERSION: ${{ '11.4' }}
       XC_WORKSPACE: ${{ 'Example/MobilliumDateFormatter.xcworkspace' }}
       XC_SCHEME: ${{ 'MobilliumDateFormatter-Example' }}
     steps:
     - uses: actions/checkout@master
     - name: Select latest Xcode
       run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
     - name: Install Dependencies
       run: |
        cd Example
        pod install --repo-update
       shell: bash
     - uses: ty0x2333/cocoapods-action@master
       with:
        additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.4.1'
        additional_lint_params: --private
     - name: Run Unit and UI Tests
       run: /usr/bin/xcodebuild test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.4.1'
